#!/bin/sh
alias g-='git switch -'
alias g='git'
alias ga.='git add .'
alias ga='git add'
alias gb='git branch'
alias gbc='git branch --show-current'
alias gbcC='echo -n $(git branch --show-current) C'
alias gbD='git branch -D'
alias gbDR='git push --delete origin`# リモートブランチを削除`'
alias gbm='git branch -m'
alias gch-='git checkout -'
alias gch='git checkout'
alias gchb='git checkout -b'
alias gchm='git checkout master'
alias gclone='git clone'
alias gcm='git commit'
alias gcmm='git commit -m'
alias gcmm1='git commit -m "1st commit" --allow-empty'
alias gd='git diff'
alias gdno='git diff --name-only'
alias gf='git fetch'
alias ghash='git log --pretty=%h HEAD -1'
alias ginit='git init'
alias gl='git log'
alias gl1='git log -1'
alias glf="git log --pretty='format:%C(yellow)%h %C(white)%s %C(red)%d %C(green)[%ad] %C(cyan)<%an>' --date=relative -40 --graph"
alias glh='git log --pretty=%h'
alias glp='git log -p'
alias gm='git merge'
alias gmauh='git merge --allow-unrelated-histories'
alias gmm='git merge $(git remote show origin | grep "HEAD branch" | cut -d ":" -f2 | tr -d " ")'
alias gmv='git mv'
alias gpack='PACKAGE="package-"`git log --pretty=%h HEAD -1`; mkdir -p $PACKAGE; gcp -vpr --parents $(echo `git diff --diff-filter=AMR --name-only $(git remote show origin | grep "HEAD branch" | cut -d ":" -f2 | tr -d " ")`) $PACKAGE `# masterとの差分ファイルをコピー`'
alias gpackH='PACKAGE="package-"`git log --pretty=%h HEAD -1`; mkdir -p $PACKAGE; gcp -vpr --parents $(echo `git diff --diff-filter=AMR --name-only HEAD^`) $PACKAGE `# 1つ前のコミットとの差分ファイルをコピー`'
alias gp='git push'
alias gpsu='git push --set-upstream'
alias gpsuo='git push --set-upstream origin $(git branch --show-current)'
alias gpull='git pull'
alias gpullomm='git pull origin main:main'
alias grebase='git rebase'
alias grebasei='git rebase -i'
alias gremote='git remote'
alias gremotea='git remote add'
alias gremotev='git remote -v'
alias greset='git reset'
alias gresethard='git reset --hard'
alias gresethardhead='git reset --hard HEAD^'
alias gresetsoft='git reset --soft'
alias gresetsofthead='git reset --soft HEAD^'
alias grm='git rm'
alias groot='cd `git rev-parse --show-toplevel`'
alias grs.='git restore .'
alias grs='git restore'
alias gs='git status'
alias gsq1='git rebase -i HEAD~2`# 一つ前のコミットにrebaseする`'
alias gst='git stash'
alias gstd='git stash apply'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gstu='git stash -u'
alias gsw-='git switch -'
alias gsw='git switch'
alias gswc='git switch --create'
alias gswm='git switch main 2> /dev/null || git switch master'
alias gui='git update-index'
alias guia='git update-index --assume-unchanged`# 一時的に変更を無視`'
alias guina='git update-index --no-assume-unchanged`# 一時的に変更を無視を解除`'
alias gunstage='git restore --staged'
alias gchours='git checkout --ours`# マージ前を採用`'
alias gchtheirs='git checkout --theirs`# マージ後を採用`'
alias gbParent='git show-branch | grep "*" | grep -v "$(git rev-parse --abbrev-ref HEAD)" | head -1 | awk -F"[]~^[]" '\''{print $2}'\'


alias aliasgit="cat $0"
alias aliasgit.=". $0"
alias aliasgit,="code $0"
